spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.1.202:1521:rac
    username: newcieccpay_test
    password: newcieccpay_test
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  thymeleaf:
    cache: false
server:
  port: 8888
